version: 2

sphinx:
  configuration: doc/source/conf.py

formats: all

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: doc/requirements-docs.txt

submodules:
  include: all
